/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rcampbell' at '10/29/15 3:30 PM' with Gradle 2.2
 *
 * @author rcampbell, @date 10/29/15 3:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
		// test
        return true;
    }
}
